### PR TITLE
Allow for modern yum-epel and resolve Foodcritic warnings

### PR DESCRIPTION
**Pull request by tas50**
This cookbook has a version constraint on yum-epel that causes chef runs to fail on modern chef releases. This is the minimum work necessary to unblock several projects that depend on it.

### CODE REVIEW

**Comment by tas50** [comment]
@4-20ma Any chance you can merge this and ship a new version of the cookbook?

**Comment by 4-20ma** [comment]
@tas50 reviewing proposed changes; any idea why travis is not pulling the latest changes to `.travis.yml`? It's failing because the config calls `rake` without a `Rakefile`. The most-recent commit 2b3260b converts from rake to delivery local mode.

Travis config (https://travis-ci.org/4-20ma/cookbook-fcgiwrap_rpm/jobs/257578588/config):
``` json
{
  "dist": "trusty",
  "sudo": false,
  "addons": {
    "apt": {
      "sources": [
        "chef-current-trusty"
      ],
      "packages": [
        "chefdk"
      ]
    }
  },
  "install": "echo \"skip bundle install\"",
  "before_script": [
    "eval \"$(chef shell-init bash)\"",
    "chef gem install emeril"
  ],
  "script": [
    "chef --version",
    "cookstyle --version",
    "foodcritic --version",
    "rake"
  ],
  "language": "ruby",
  "group": "stable",
  "os": "linux"
}
```

**Comment by shoekstra** [comment]
@4-20ma could you try rerunning the tests?  Travis is referring to commit 035e6f1 and not the latest commit.

**Comment by 4-20ma** [comment]
Need to close/reopen PR in order for travis-ci to pull in new `.travis.yml` config...

Reference: https://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit

**Comment by 4-20ma** [comment]
OK, @tas50, it looks like travis-ci is now building using delivery local mode. Can you resolve the errors so we can merge this PR?

**Comment by tas50** [comment]
@4-20ma I fixed the specs to pass locally. This *should* be green in a bit

**Pull request closed without merging**
